remix guide color mode ssr enhancement
chakra-ui/chakra-ui-docs pull request #1002
Opened 2022-09-20 07:56 UTC by alexinfurs

## 📝 Description

This PR improves Color Mode SSR with Remix.run

## ⛳️ Current behavior (updates)

Currently, cookies are loaded within loader, so if you switch the theme and then do a client routing, it switches again to the previous theme
Also, the server doesn't include the relevant classes to html and body tags, so if you disable JavaScript the theme is not correctly rendered

## 🚀 New behavior

With this PR, cookies are overridden on the client side to avoid unwanted theme switch and the server adds classes to html and body tags to correctly render the theme without JavaScript enabled in the client.

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

2023-01-08 18:55 UTC, aacevski requested changes
Hey @alexinfurs, sorry for leaving this PR stale for so long, this looks great. I just have one thing that we could add. Instead of the last part for community boilerplates, we could replace it with a CodeSandbox example and we can see how Chakra UI works with Remix in one rounded example.

2023-01-08 18:55 UTC, aacevski commented on content/getting-started/remix-guide.mdx
> +      : null)}
```suggestion
    {...colorMode
      && {
          "data-theme": colorMode,
          "style": { colorScheme: colorMode },
        }
      }
```

2023-01-08 18:55 UTC, aacevski commented on content/getting-started/remix-guide.mdx
> +      } : null )}
```suggestion
      {...colorMode && {
        className: `chakra-ui-${colorMode}`
      }}
```

2023-01-12 19:45 UTC, aacevski commented
One more question, why aren't we using hydrateRoot like in the official Remix guide? Maybe we should update.

2023-01-13 09:57 UTC, alexinfurs commented
I made just the minimal changes from the previous guide.
We definitely should update here, I already updated my projects to hydrateRoot and renderToPipeableStream to take advantages from React 18 streaming feature

2023-01-15 22:44 UTC, aacevski approved these changes

2023-02-19 21:13 UTC, merged