feature(docs): link component theming docs
chakra-ui/chakra-ui-docs pull request #1102
Opened 2022-10-11 20:46 UTC by umrkhn

Closes #1076 

## 📝 Description

Adds theming documentation for the `Link` component.

## 💣 Is this a breaking change (Yes/No):

No

2022-10-12 11:18 UTC, nikolovlazar requested changes
@umrkhn we've updated the single part component theming doc template to provide more value to the users by including more use cases and guides. Please check out the new structure and optimize your PR according to it.

2022-10-14 09:38 UTC, nikolovlazar requested changes
The content looks decent, but we've got work to do in the Sandbox. Let's revisit the custom theme, create new variants that are suitable for the `Link` component, and use them in the app.

2022-10-14 09:38 UTC, nikolovlazar commented on configs/sandpack-contents/component-theming/link.js
> +        rounded="full"
Can you add `aria-label="change theme"` here?

2022-10-14 09:38 UTC, nikolovlazar commented on configs/sandpack-contents/component-theming/link.js
> +})
Can you double check these? Some of the properties like `borderRadius` doesn't make sense to be applied to the `Link` component. I know these are from the `Button` theming examples, but let's make new examples for the `Link` component. Try adding some basic base styles, and change a few things on hover, like font weight, add an underline (solid or dashed), maybe scale it a little etc.

Also, make sure you're using them in the examples. I can see you're defining these here, but you're not using the custom size and variant in any of the links in the app.

2022-10-14 09:38 UTC, nikolovlazar commented on content/docs/components/link/theming.mdx
> +```
There are changes in this block. Check out the template to see them.

2022-10-22 12:44 UTC, umrkhn reviewed
updated changes as mentioned.

2022-10-23 07:40 UTC, nikolovlazar approved these changes
There's one issue left, but I'll take care of it. Thanks for contributing to the Link theming docs @umrkhn 🙌

2022-10-23 07:40 UTC, merged

2022-10-23 07:40 UTC, nikolovlazar commented
@allcontributors please add @umrkhn for docs.