docs: added heading theming docs following the new template
chakra-ui/chakra-ui-docs pull request #1109
Opened 2022-10-13 15:29 UTC by pybash1

Closes #1074 

## 📝 Description

> Added docs for theming headings.

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Adds docs for theming headings

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information

2022-10-14 08:25 UTC, nikolovlazar commented on content/docs/components/heading/theming.mdx
> +    border: "0px",
The Heading doesn't have a border by default, so you don't need to specify it here. It's a better idea to modify the `fontFamily` and/or `fontWeight` instead.

2022-10-14 08:26 UTC, nikolovlazar commented on content/docs/components/heading/theming.mdx
> +After customizing the divider theme, we can import it in our theme file and add it in the components property:
You've got `divider` instead of `heading` here.

2022-10-14 08:26 UTC, nikolovlazar commented on content/docs/components/heading/theming.mdx
> +import { headingTheme } from './components/divider.ts'
You're importing from `divider.ts`.

2022-10-14 08:26 UTC, nikolovlazar commented on content/docs/components/heading/theming.mdx
> +> This is a crucial step to make sure that any changes that we make to the divider theme are applied.
You've got `divider` instead of `heading`.

2022-10-14 08:26 UTC, nikolovlazar commented on content/docs/components/heading/theming.mdx
> +```
This block has been changed. Check out the template to see the latest changes.

2022-10-14 08:28 UTC, nikolovlazar commented on content/docs/components/heading/theming.mdx
> +})
This styling doesn't make sense for the `Heading` component. The `Heading` is a simple component. We can just change its `fontFamily`, `fontWeight`, and potentially adding a border at the bottom of it (underline). Also, rename `thicc` to something more suitable, like `underline` if you're adding a bottom border.

2022-10-14 08:28 UTC, nikolovlazar commented on content/docs/components/heading/theming.mdx
> +<Divider variant="thicc">...</Divider>
Change this to reflect the new variant and the `Heading` component.

2022-10-14 08:30 UTC, nikolovlazar commented on content/docs/components/heading/theming.mdx
> +```
No variant utilizes the `colorScheme`, so I'd either remove this, or create a custom variant that utilizes the `colorScheme` and provide examples for it. Also, you've got `Divider` here as well.

2022-10-14 08:30 UTC, nikolovlazar commented on content/docs/components/heading/theming.mdx
> +<Divider size="xl" variant="thicc" colorScheme="brand">...</Divider>
You're showcasing the `Divider` here. Also, remove the `colorScheme`.

2022-10-14 08:31 UTC, nikolovlazar commented on configs/sandpack-contents/component-theming/heading.js
> +              <Heading variant="thicc">Hover me(in dark mode)</Heading>
Rename `thicc`.

2022-10-14 08:38 UTC, nikolovlazar commented on configs/sandpack-contents/component-theming/heading.js
> +})`,
Get this to reflect on your changes (variant, size, and potentially color scheme if you provide a variant that utilizes it).

2022-10-17 09:23 UTC, nikolovlazar requested changes
Just a few more edits and we're good to go.

2022-10-17 09:23 UTC, nikolovlazar commented on content/docs/components/heading/theming.mdx
> +import { headingTheme } from './components/heading.ts'
Remove the `.ts` extension from the import.

2022-10-17 09:23 UTC, nikolovlazar commented on content/docs/components/heading/theming.mdx
> +```
This block is still not updated. It should just be this paragraph:

```markdown
Every time you're adding anything new to the theme, you'd need to run the CLI
command to get proper autocomplete in your IDE. You can learn more about the CLI
tool [here](/docs/styled-system/cli).
```

2022-10-17 09:23 UTC, nikolovlazar commented on content/docs/components/heading/theming.mdx
> +```
Also, you should place this at the end of the `## Adding a custom variant` section.

2022-10-17 09:23 UTC, nikolovlazar commented on configs/sandpack-contents/component-theming/heading.js
> +  App: `import { Box, SimpleGrid, IconButton, Center, Heading, useColorMode } from "@chakra-ui/react";
You're not using the `Center` component, so you can remove it from the imports.

2022-10-17 09:23 UTC, nikolovlazar commented on configs/sandpack-contents/component-theming/heading.js
> +                rounded="full"
The `IconButton` requires an `aria-label` prop. Put this as the first prop: `aria-label="toggle theme"`

2022-10-17 09:23 UTC, nikolovlazar commented on configs/sandpack-contents/component-theming/heading.js
> +import { headingTheme } from "./theme/components/Heading.ts";
Remove the `.ts` extension from the import.

2022-10-17 13:51 UTC, nikolovlazar requested changes

2022-10-17 13:51 UTC, nikolovlazar commented on content/docs/components/heading/theming.mdx
> +The `Heading` component is a single part component. All of the styling is applied
Let's add an `## Overview` heading here.

2022-10-17 13:51 UTC, nikolovlazar commented on content/docs/components/heading/theming.mdx
> +import { headingTheme } from './components/heading.ts'
Still present.

2022-10-17 13:51 UTC, nikolovlazar commented on content/docs/components/heading/theming.mdx
> +```
Still not changed.

2022-10-18 12:36 UTC, pybash1 commented
@nikolovlazar extremely sorry. I believe I had forgotten to push my local changes. It should be fixed now.

2022-10-18 12:52 UTC, nikolovlazar approved these changes
Looking good!

2022-10-18 12:52 UTC, merged

2022-10-18 12:52 UTC, nikolovlazar commented
@allcontributors please add @pybash1 for docs.

2022-10-18 12:53 UTC, nikolovlazar commented
@pybash1 thanks for contributing to the heading theming docs 🙌

2022-10-18 15:09 UTC, pybash1 commented
@nikolovlazar the pleasure was mine.