feat(docs): add ```Accordion``` theming docs
chakra-ui/chakra-ui-docs pull request #1110
Opened 2022-10-14 00:07 UTC by HariVP03

Closes #1035 

## 📝 Description
Adds the theming docs for ```Accordion``` component.

## ⛳️ Current behavior (updates)
There are no theming docs for ```Accordion``` currently

## 🚀 New behavior
Adds the theming docs for ```Accordion``` component.

## 💣 Is this a breaking change (Yes/No):
No

2022-10-14 08:20 UTC, nikolovlazar requested changes
Thanks for opening this PR, @HariVP03. But I can see you're not following the template I've provided in the GitHub Issue #1035. Could you refactor your PR to reflect on that?

2022-10-14 11:50 UTC, HariVP03 commented
> 

Sure

2022-10-15 20:15 UTC, HariVP03 commented
@nikolovlazar I've made the necessary changes to follow the new format

2022-10-17 10:02 UTC, nikolovlazar requested changes
Nearly there, @HariVP03!

I noticed you've got a couple of `.ts` extensions left in the imports. I've also provided you with the accordion anatomy illustration code. Apply these changes and we're good to go!

2022-10-17 10:02 UTC, nikolovlazar commented on content/docs/components/accordion/theming.mdx
> +
I've prepared an anatomy illustration for you. Grab [this code](https://gist.github.com/nikolovlazar/bec580e8d8d2eb12bed7c7aa6086275a) and add the following section as the first:

```markdown
## Anatomy

- A: `root`
- B: `container`
- C: `button`
- D: `panel`
- E: `icon`

[PLACE THE ILLUSTRATION CODE HERE]
```

2022-10-17 11:50 UTC, nikolovlazar approved these changes
All good!

2022-10-17 11:52 UTC, merged

2022-10-17 11:52 UTC, nikolovlazar commented
@allcontributors please add @HariVP03 for docs.