Update nextjs-guide.mdx
chakra-ui/chakra-ui-docs pull request #1390
Opened 2023-01-26 13:52 UTC by timreach

Import theme from _app, where it is defined. Docs currently suggest importing from a theme file which does not exist. Either demonstrate the creation of this file or apply these suggested small changes.

Closes # 

## 📝 Description

> Add a brief description

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

## 💣 Is this a breaking change (Yes/No):

## 📝 Additional Information

2023-01-29 20:30 UTC, aacevski requested changes
Hey, thank you for your contribution 💖 Some small changes and we should be good!

2023-01-29 20:30 UTC, aacevski commented on content/getting-started/nextjs-guide.mdx
> +import theme from './_app'
```suggestion
import { theme } from './_app'
```

2023-01-29 20:30 UTC, aacevski commented on content/getting-started/nextjs-guide.mdx
> +export {theme}
Remove this and remove part and do export right where the const of the theme is defined.

export theme = extendTheme(...)

2023-04-10 09:23 UTC, noobinthisgame approved these changes
Looks like this ready 😄

2023-04-16 21:08 UTC, merged