docs/checkbox hooks page
chakra-ui/chakra-ui-docs pull request #141
Opened 2021-12-16 21:55 UTC by noobinthisgame

Closes #72 

## 📝 Description

Added two new pages for the useCheckbox and useCheckboxGroup hooks that describe their functionality. Linked the pages in the checkbox documentation.

## ⛳️ Current behavior (updates)

Only a small description about the hooks in the Checkbox documentation.

## 🚀 New behavior

Two new detailed pages that explain how the useCheckbox and useCheckboxGroup hooks can be used.

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information
-

2021-12-17 05:18 UTC, lazarnikolov94 commented
This is great @noobinthisgame! Could you also write up some examples? Here's a little codesandbox I created that can help you get started: https://codesandbox.io/s/custom-checkbox-using-usecheckbox-hook-82pgi?file=/src/index.tsx

2021-12-17 06:14 UTC, noobinthisgame commented
Ye of course! This is still work in progress, I didn't find how zo make a draft PR. Thanks for the codesanbox! 😁

2022-01-09 20:17 UTC, noobinthisgame commented
FYI back from vacation and back on this!

2022-01-13 10:17 UTC, noobinthisgame commented
To make it easier to document and easier to understand I made some changes to the main code. Thus this PR is depending on those changes to be added and merged https://github.com/chakra-ui/chakra-ui/pull/5375

2022-01-30 20:13 UTC, noobinthisgame commented
@nikolovlazar I finally found some time to get this done! :) Ready for review now. Could you please also check what happens when you change the strings to numbers in the values in the example for useCheckboxGroup. Seemed like there is something wrong when using numbers, not sure tho if it's a bug.

2022-02-01 07:40 UTC, nikolovlazar requested changes
@noobinthisgame this is a bug indeed. I've opened a PR in the main repo: https://github.com/chakra-ui/chakra-ui/pull/5502 that potentially fixes this issue. Thanks for letting me know!

Other than that, let's make the types of the `useCheckboxGroup` hook a bit more abstract, because they're pushing on the description, and the props table looks funky:
<img width="816" alt="CleanShot 2022-02-01 at 08 39 50@2x" src="https://user-images.githubusercontent.com/5396211/151929752-61ffbc94-57ee-494b-8504-3ab604f8be7e.png">

2022-02-01 09:01 UTC, noobinthisgame commented
@nikolovlazar indeed those types were a bit long. I pushed some simplifying changes :)

2022-02-02 06:42 UTC, nikolovlazar requested changes
Other than this typo, everything looks good and it's ready to be merged! 👌

2022-02-02 06:42 UTC, nikolovlazar commented on pages/docs/hooks/use-checkbox.mdx
> +`useCheckbox` is a custom hook used to provide checkbox functionality, aswell as
```suggestion
`useCheckbox` is a custom hook used to provide checkbox functionality, as well as
```

Missing space between `as` and `well`: `aswell` -> `as well`

2022-02-02 07:46 UTC, noobinthisgame commented
Fixed

2022-02-02 07:53 UTC, merged

2022-05-05 09:01 UTC, nikolovlazar commented on pages/docs/hooks/use-checkbox-group.mdx
> +        <input {...getInputProps()} hidden />
That's interesting @julia-allyce! I tried the example csb above and I didn't get the focus as well. Can you produce a CSB example (maybe use the one above) with the focus implemented?