docs: fix missing children in theming example
chakra-ui/chakra-ui-docs pull request #284
Opened 2022-02-05 17:16 UTC by aaarichter

## 📝 Description

Adds `{children}`to theming example @ https://chakra-ui.com/docs/theming/component-style#return-value

## ⛳️ Current behavior (updates)

Theming example misses using `{children}`, which was destructed from props in line 222

## 🚀 New behavior

Adds `{children}`to theming example

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

2022-02-07 06:31 UTC, nikolovlazar commented
Good catch, @aaarichter! Although, I'd prefer if we remove the `children` destructuring completely, so it becomes a part of the `...rest` spread. Since we're not doing anything specific to the `children`, destructuring it and manually rendering it seems redundant. So let's remove it. What do you think?

2022-02-08 06:27 UTC, nikolovlazar requested changes
Good catch, @aaarichter! Although, I'd prefer if we remove the `children` destructuring completely, so it becomes a part of the `...rest` spread. Since we're not doing anything specific to the `children`, destructuring it and manually rendering it seems redundant. So let's remove it. What do you think?

2022-02-08 08:52 UTC, aaarichter commented
@nikolovlazar feedback addressed. 

I wasn't sure which way to write it. Destructing `children` in this example is redundant but from a understanding point of view a bit clearer (to me)

2022-02-08 19:19 UTC, merged

2022-02-08 19:19 UTC, nikolovlazar commented
@allcontributors please add @aaarichter for bugs.