Fix/double sponsor entries
chakra-ui/chakra-ui-docs pull request #419
Opened 2022-03-12 13:58 UTC by m4x3d

Closes #330 

## 📝 Description

Adds a filter for fetched sponsors from opencollective by the opencollective profile link to avoid double entries at the sponsors section. Also makes the link props on the organization sponsors conditional by the presence of the website link.

## ⛳️ Current behavior (updates)

- double entries on the sponsors section on the landingpage (see the screenshot in the issue)
- a tag without href for some organization sponsors without given website informations

## 🚀 New behavior

- sponsors are filtered now by the opencollective profile link
- conditional link props for organization sponsors depending on the website link

## 💣 Is this a breaking change (Yes/No):

No

2022-03-12 18:45 UTC, noobinthisgame requested changes

2022-03-12 18:45 UTC, noobinthisgame commented on scripts/avatars.ts
> +  const companies = sponsors.filter((sponsor: any) => sponsor.type === 'ORGANIZATION')
Let's try to have all those anys typed properly :)

2022-03-13 09:35 UTC, nikolovlazar approved these changes
LGTM! Just resolve the conflicts and it'll be ready to merge.

2022-03-13 20:35 UTC, m4x3d commented
@nikolovlazar 
I just rebased the main branch. Probably it will have conflicts after the daily update PR again so I will check it tomorrow morning again.

2022-03-13 20:38 UTC, merged