fix(alert): update second composition code example
chakra-ui/chakra-ui-docs pull request #535
Opened 2022-04-15 16:25 UTC by TylerAPfledderer

## 📝 Description

The second live code example for the `Alert` doc's [Composition section](http://localhost:3000/docs/components/feedback/alert#composition) shows a `CloseButton` component, but no example of functionality to assure the user that the removal of the alert happens with no props passed to the wrapper or within the component, but through some other means outside of the scope.

This PR also tidies up the layout of the example in respect to mobile view, where the `CloseButton` component stays within the flow of the flexbox rendered by `Alert` and positioned relatively. This keeps any content from potentially overlapping this component should a user play around with the example.

## ⛳️ Current behavior (updates)

The user might try to press the close button, but the alert will not close

## 🚀 New behavior

Include in the example code `useDisclosure` and handling of `CloseButton` on click so the the alert will disappear when this button is selected.

2022-04-16 06:33 UTC, nikolovlazar requested changes

2022-04-16 06:33 UTC, nikolovlazar commented on pages/docs/components/feedback/alert.mdx
> +          top='-4px'
Let's use `{-1}` instead of `-4px`. It compiles to `-4px` as well, but it's much cleaner.

2022-04-16 06:33 UTC, nikolovlazar commented on pages/docs/components/feedback/alert.mdx
> +  const { isOpen, onClose } = useDisclosure({ defaultIsOpen: true })
I love that you expanded on this example and made it functional. How about adding a simple Toggle button that can bring up the alert again after we've closed it?

2022-04-17 19:59 UTC, TylerAPfledderer commented
@nikolovlazar good to go for a re-review! 🎉 🌮

2022-04-18 04:33 UTC, merged