Tutorial/layout components
chakra-ui/chakra-ui-docs pull request #620
Opened 2022-05-18 13:52 UTC by estheragbaje

Closes #529 

## 📝 Description

Created tutorial section for layout components

## ⛳️ Current behavior (updates)

We plan to populate the tutorial section.

## 🚀 New behavior

N/A

## 💣 Is this a breaking change (Yes/No):

No
## 📝 Additional Information

2022-05-20 20:08 UTC, noobinthisgame requested changes
Thanks @estheragbaje for your work on this ! I think it looks really good already ! 

What I would love to see is a little more usage of the codesandbox on the right side. Maybe you could put a more advanced example of layout components usage as initial content for the users to have something to experiment with. Maybe something where you use multiple components. You can expand this https://github.com/chakra-ui/chakra-ui-docs/blob/main/layouts/tutorial.tsx#L85-L98 with a new `App.tsx`,  no need for the `package.json` :)

2022-05-20 20:08 UTC, noobinthisgame commented on configs/sandpack-contents/tutorial/package.ts
> +    "@chakra-ui/icons": "1.1.7",
I assume this dependency is one you want to use in your tutorial? You need to add it here for it to work properly in the sandbox: https://github.com/chakra-ui/chakra-ui-docs/blob/main/src/components/tutorial/tutorial-container.tsx#L85-L91

2022-05-20 20:08 UTC, noobinthisgame commented on configs/sandpack-contents/tutorial/package.ts
> +    "@chakra-ui/icons": "1.1.7",
This package.json is just an example file and has no real impact on the sandbox.

2022-05-20 20:08 UTC, noobinthisgame commented on pages/tutorial/layout-components.mdx
>  description: 'TBD'
Kindly add a small description here :)

2022-08-11 08:28 UTC, segunadebayo commented
Closing this since we're no longer shipping Tutorials for now.

2022-08-11 08:28 UTC, closed without merging