docs: add initialValue to fix a type error of ref
chakra-ui/chakra-ui-docs pull request #671
Opened 2022-05-30 14:31 UTC by youngvform

## 📝 Description

> When i use modal examples(like InitialFocus), i get this type error.

`Type 'MutableRefObject<undefined>' is not assignable to type 'LegacyRef<HTMLButtonElement> | undefined'.
  Type 'MutableRefObject<undefined>' is not assignable to type 'RefObject<HTMLButtonElement>'.
    Types of property 'current' are incompatible.
      Type 'undefined' is not assignable to type 'HTMLButtonElement | null'.ts(2322)
index.d.ts(137, 9): The expected type comes from property 'ref' which is declared here on type 'IntrinsicAttributes & OmitCommonProps<DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, keyof ButtonProps> & ButtonProps & { ...; }'
`
To fix this error, i add null for initialValue

## ⛳️ Current behavior (updates)

> Type incompatible error occurs

## 🚀 New behavior

> The error disappear

## 💣 Is this a breaking change (Yes/No): No

2022-05-31 05:42 UTC, nikolovlazar requested changes
The `useRef` hook is generic, so instead of passing `null` we should precisely define the type.

2022-05-31 05:42 UTC, nikolovlazar commented on pages/docs/components/overlay/modal.mdx
> +  const finalRef = React.useRef(null)
```suggestion
  const finalRef = React.useRef<HTMLDivElement>()
```

2022-05-31 05:42 UTC, nikolovlazar commented on pages/docs/components/overlay/modal.mdx
> +  const finalRef = React.useRef(null)
```suggestion
  const initialRef = React.useRef<HTMLInputElement>()
  const finalRef = React.useRef<HTMLButtonElement>()
```

2022-05-31 05:42 UTC, nikolovlazar commented on pages/docs/components/overlay/modal.mdx
> +  const btnRef = React.useRef(null)
```suggestion
  const btnRef = React.useRef<HTMLButtonElement>()
```

2022-05-31 14:16 UTC, nikolovlazar commented
@youngvform that's actually it!

2022-06-03 06:29 UTC, nikolovlazar approved these changes
Actually it's okay. We can add `null`s. Thanks for opening this PR, @youngvform!

2022-06-03 06:32 UTC, merged

2022-06-07 14:30 UTC, youngvform commented
@nikolovlazar Thank you for your kind review!
My typescript config was [generated by next](https://nextjs.org/docs/basic-features/typescript#create-next-app-support)
I think it's [this file](https://github.com/vercel/next.js/blob/canary/packages/create-next-app/templates/typescript/tsconfig.json)
And perhaps it has something to do with`"strictNullChecks": true,`
You can see the error on [code sandbox](https://codesandbox.io/s/upbeat-jepsen-vmh71e?file=/src/Modal.tsx)

Thank you again!