docs(guides): add remix guide page
chakra-ui/chakra-ui-docs pull request #83
Opened 2021-11-29 22:16 UTC by noobinthisgame

Closes #63 

## 📝 Description

Adds a guide to get started with Remix.

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

2021-11-29 22:17 UTC, noobinthisgame commented
@lazarnikolov94 Please lmk if you have something to add to this Remix guide.

2021-11-30 21:36 UTC, lazarnikolov94 commented
I haven't gotten into Remix that much just yet, so I don't really know if there are any additional stuff to mention. I would suggest adding a little blockquote at the top saying that this document might be a "work-in-progress" and call out people who know Remix to contribute to the documentation.

2021-11-30 21:37 UTC, lazarnikolov94 requested changes
I haven't gotten into Remix that much just yet, so I don't really know if there are any additional stuff to mention. I would suggest adding a little blockquote at the top saying that this document might be a "work-in-progress" and call out people who know Remix to contribute to the documentation.

2021-11-30 21:43 UTC, noobinthisgame commented
Alright :) Good idea will do so.

2021-12-01 12:25 UTC, noobinthisgame commented
Good catch thanks! Will change that :)

2021-12-02 20:21 UTC, lazarnikolov94 commented
@noobinthisgame let me know when it's ready to be reviewed again

2021-12-02 20:22 UTC, noobinthisgame commented
@lazarnikolov94 it should be ready with your suggestions implemented

2021-12-02 20:23 UTC, lazarnikolov94 commented
Awesome! I'll do a complete review tomorrow. Looks great btw!

2021-12-02 20:24 UTC, lazarnikolov94 commented
> @lazarnikolov94 it should be ready with your suggestions implemented

Awesome! I'll do a complete review tomorrow. Looks great btw!

2021-12-02 20:26 UTC, noobinthisgame commented
Cool thanks!!!

2021-12-03 05:17 UTC, lazarnikolov94 commented
I see @primos63 wrote a good guide on Remix here: https://github.com/chakra-ui/chakra-ui/issues/5166 Maybe you could apply these changes and update this PR.

2021-12-04 21:18 UTC, noobinthisgame commented
@lazarnikolov94 I added more details to the provider setup as suggested by @primos63.

2021-12-06 05:04 UTC, lazarnikolov94 requested changes
Just minor word play. Looks good btw 👌

2021-12-06 05:04 UTC, lazarnikolov94 commented on pages/guides/getting-started/remix-guide.mdx
> +> 🚨 As of now yarn is not officially supported in Remix projects, use with care!
> 🚨 Right now yarn is not officially supported in Remix projects, so use it with care!

2021-12-06 05:04 UTC, lazarnikolov94 commented on pages/guides/getting-started/remix-guide.mdx
> +> built something with Remix and Chakra UI 😃
> This guide is still work in progress! Feel free to contribute if you have
> something built with Remix and Chakra UI 😃

2021-12-06 17:09 UTC, noobinthisgame commented
@lazarnikolov94 texts are changed :)

2021-12-07 07:33 UTC, merged